Resources:
  IAMUserETL:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: ETLPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 's3:Get*'
                  - 's3:List*'
                  - 's3:Put*'
                  - 's3:DeleteObject*'
                  - 's3:RestoreObject'
                Resource: !Join ['', ['arn:aws:s3:::', 'staging-', !Ref 'AWS::AccountId', '/*']]
  StagingBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join
        - '-'
        - - 'staging'
          - !Ref 'AWS::AccountId'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
